"use client";
import { useEffect,useMemo,useState } from "react";
import { ArrowRight,BarChart3,BookOpen,Braces,Check,ChevronRight,Clock3,FlaskConical,RefreshCw,ScanSearch,ShieldCheck,Sparkles,Terminal,Unplug } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { FloatingLabelInput } from "@/components/spectrumui/floating-label-input";
import { AgentSteps } from "@/components/spectrumui/blocks/ai-assistants/agent-steps";
import type { ToolCall } from "@/components/spectrumui/blocks/ai-assistants/types";
import { illustrativeSnapshots,priceImmediacy,type MarketSnapshot,type Side } from "@/lib/immediacy";

const assets=[{symbol:"RNVDAUSDT",label:"rNVDA"},{symbol:"RTSLAUSDT",label:"rTSLA"},{symbol:"RQQQUSDT",label:"rQQQ"}];
const money=(n:number,digits=2)=>new Intl.NumberFormat("en-US",{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(n);
const compact=(n:number)=>new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:1}).format(n);
const signed=(n:number,suffix="")=>`${n>0?"+":n<0?"−":""}${money(Math.abs(n))}${suffix}`;
const time=(timestamp:number)=>timestamp?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit",timeZoneName:"short"}).format(timestamp):"illustrative";

export default function Desk(){
  const[symbol,setSymbol]=useState("RNVDAUSDT"),[side,setSide]=useState<Side>("buy"),[notional,setNotional]=useState("2500");
  const[snapshot,setSnapshot]=useState<MarketSnapshot>(illustrativeSnapshots.RNVDAUSDT),[loading,setLoading]=useState(true),[marketError,setMarketError]=useState("");
  const[tab,setTab]=useState("decision"),[question,setQuestion]=useState("Is this weekend quote information—or am I paying for thin liquidity?");
  const[aiText,setAiText]=useState(""),[aiError,setAiError]=useState(""),[aiLoading,setAiLoading]=useState(false);

  async function loadMarket(nextSymbol=symbol){setLoading(true);setMarketError("");try{const response=await fetch(`/api/market?symbol=${nextSymbol}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error("Live market data unavailable.");setSnapshot(data)}catch{setSnapshot(illustrativeSnapshots[nextSymbol]);setMarketError("Live Bitget data is unavailable in this preview. Showing an explicitly illustrative book instead.")}finally{setLoading(false)}}
  useEffect(()=>{void loadMarket(symbol)},[symbol]);
  const parsedNotional=Number(notional),inputError=!Number.isFinite(parsedNotional)||parsedNotional<=0||parsedNotional>1_000_000;
  const result=useMemo(()=>{try{return priceImmediacy(snapshot,parsedNotional,side)}catch{return priceImmediacy(snapshot,2500,side)}},[snapshot,parsedNotional,side]);

  async function askQwen(){setAiLoading(true);setAiError("");setAiText("");try{const response=await fetch("/api/research",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({question,asset:snapshot.asset,side,notional:parsedNotional,source:snapshot.source,session:snapshot.session,metrics:{posture:result.posture,rationale:result.rationale,spreadBps:result.spreadBps,impactBps:result.impactBps,anchorBasisPct:result.anchorBasisPct,fillRatio:result.fillRatio}})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Qwen request failed.");setAiText(data.output)}catch(error){setAiError(error instanceof Error?error.message:"Qwen request failed.")}finally{setAiLoading(false)}}

  const trace:ToolCall[]=[
    {id:"ticker",name:"read_bitget_ticker",status:loading?"running":snapshot.source==="live"?"success":"error",result:loading?"Requesting a public, read-only Bitget market snapshot.":snapshot.source==="live"?`${snapshot.symbol} bid ${money(snapshot.bid)}, ask ${money(snapshot.ask)}. Public Bitget v3 market endpoint; no account key.`:"Live request failed. Illustrative values are labeled and kept separate."},
    {id:"book",name:"inspect_visible_book",status:loading?"pending":"success",result:`${snapshot.asks.length} ask levels and ${snapshot.bids.length} bid levels inspected. ${money(result.fillRatio*100)}% of the requested size is visible.`},
    {id:"anchor",name:"derive_us_session_anchor",status:loading?"pending":"success",result:`${money(snapshot.anchor)} USDT from the latest completed 3–4 PM New York hourly rToken candle. This is a venue anchor, not the underlying Nasdaq print.`},
    {id:"price",name:"price_cost_of_immediacy",status:loading?"pending":"success",result:`${money(result.spreadBps)} bps spread; ${money(result.impactBps)} bps estimated market-order impact at ${money(parsedNotional||2500)} USDT.`},
    {id:"qwen",name:"qwen_explain_evidence",status:aiLoading?"running":aiText?"success":"cancelled",result:aiText||"No model output is displayed until a real Qwen request succeeds."},
  ];

  return <div className="desk"><a className="skip-link" href="#workbench">Skip to workbench</a>
    <header className="topbar"><a className="wordmark" href="/">veyra<span>/</span></a><span className="top-divider"/><span className="top-label">AGENT DESK</span><div className="top-right"><span className="demo-tag"><FlaskConical size={14}/>Public demo</span><span className="read-only"><ShieldCheck size={14}/>No execution</span></div></header>
    <main><div className="page-title"><div><p className="eyebrow">AI TRADING DESK / RTOKEN MARKET STRUCTURE</p><h1>Trade now—or pay less for patience?</h1><p>Veyra prices the cost of immediacy while the US cash market is asleep.</p></div><Button variant="outline" onClick={()=>loadMarket()} disabled={loading}><RefreshCw size={14} className={loading?"spin":""}/>{loading?"Refreshing":"Refresh book"}</Button></div>
      <div className="flow-strip" aria-label="Demo workflow"><span><b>01</b> Choose rToken + size</span><ChevronRight/><span><b>02</b> Read Bitget book</span><ChevronRight/><span><b>03</b> Price immediacy</span><ChevronRight/><span><b>04</b> Explain evidence</span></div>
      <div className="workbench" id="workbench">
        <Card className="input-panel"><div className="section-heading"><span><Terminal size={16}/>Trade question</span><span className="mono muted">01</span></div><div className="input-body">
          <div className="subheading"><h2>rToken</h2><span className="small-label">BITGET SPOT</span></div><div className="asset-grid">{assets.map(item=><Button key={item.symbol} variant={symbol===item.symbol?"default":"outline"} onClick={()=>setSymbol(item.symbol)}>{item.label}</Button>)}</div>
          <div className="subheading input-separator"><h2>Direction</h2><span className="small-label">HYPOTHETICAL</span></div><div className="side-grid"><Button variant={side==="buy"?"default":"outline"} onClick={()=>setSide("buy")}>Buy now</Button><Button variant={side==="sell"?"default":"outline"} onClick={()=>setSide("sell")}>Sell now</Button></div>
          <div className="size-input"><FloatingLabelInput id="order-size" label="Order size (USDT)" type="number" min={1} max={1000000} step="any" value={notional} onChange={event=>setNotional(event.target.value)}/></div>{inputError&&<p className="error" role="alert">Use a size from 1 to 1,000,000 USDT.</p>}
          <div className="quote-mini"><div><span>Best bid</span><strong>{money(snapshot.bid)}</strong></div><div><span>Best ask</span><strong>{money(snapshot.ask)}</strong></div><div><span>US-session anchor</span><strong>{money(snapshot.anchor)}</strong></div></div>
          <Button className="run-button" onClick={()=>setTab("decision")} disabled={inputError||loading}>Price this decision<ArrowRight size={16}/></Button><p className="local-note"><Braces size={13}/>Read-only market data · no order route</p>
        </div></Card>

        <div className="result-panel"><Tabs value={tab} onValueChange={setTab}><div className="result-nav"><TabsList><TabsTrigger value="decision">Decision</TabsTrigger><TabsTrigger value="book">Book math</TabsTrigger><TabsTrigger value="evidence">Evidence</TabsTrigger></TabsList><span className={`source-pill ${snapshot.source}`}>{loading?"FETCHING":snapshot.source==="live"?"LIVE BITGET":"ILLUSTRATIVE"}</span></div>
          {marketError&&<p className="stale-note" role="status">{marketError}</p>}
          <TabsContent value="decision"><Card className="decision-card"><div className="decision-top"><div><p className="eyebrow">EXECUTION POSTURE / {side.toUpperCase()}</p><div className="posture">{result.posture}</div></div><div className={`session-badge ${snapshot.session}`}><span/>{snapshot.session==="open"?"US cash open":"US cash closed"}</div></div><p className="decision-rationale">{result.rationale}</p><div className="metric-grid"><div><span>Book vs anchor</span><strong className={Math.abs(result.anchorBasisPct)>=1.5?"loss":""}>{signed(result.anchorBasisPct,"%")}</strong><small>current mid</small></div><div><span>Quoted spread</span><strong>{money(result.spreadBps)} bps</strong><small>bid to ask</small></div><div><span>Size impact</span><strong>{money(result.impactBps)} bps</strong><small>estimated fill</small></div></div></Card>
            <div className="section-title"><div><h2>Why Veyra reached this posture</h2><p>Rules first. Qwen can explain, but it cannot change the math.</p></div><span className="small-label">AUDITABLE</span></div><div className="evidence-lines"><div><span>01</span><p><strong>{money(result.fillRatio*100)}% visible fill.</strong> The requested {money(parsedNotional||2500)} USDT walks {result.fills.length} {result.fills.length===1?"level":"levels"}.</p></div><div><span>02</span><p><strong>{money(result.depth25bps)} USDT near-touch depth.</strong> Measured within 25 bps of mid on the {side} side.</p></div><div><span>03</span><p><strong>{signed(result.executionVsAnchorPct,"%")} versus the session anchor.</strong> This prices immediacy; it does not predict Monday.</p></div></div>
            <Button variant="outline" className="compare-button" onClick={()=>setTab("book")}>Inspect the fill calculation<ArrowRight size={15}/></Button>
          </TabsContent>
          <TabsContent value="book"><Card className="book-card"><div className="book-summary"><div><span>Requested</span><strong>{money(parsedNotional||2500)} USDT</strong></div><div><span>Estimated average</span><strong>{money(result.averageFill)}</strong></div><div><span>Book cost vs mid</span><strong>{money(result.estimatedBookCost)} USDT</strong></div></div><Table><TableHeader><TableRow><TableHead>Level</TableHead><TableHead className="numeric">Price</TableHead><TableHead className="numeric">Quantity used</TableHead><TableHead className="numeric">Notional</TableHead></TableRow></TableHeader><TableBody>{result.fills.map((fill,index)=><TableRow key={`${fill.price}-${index}`}><TableCell className="muted">{String(index+1).padStart(2,"0")}</TableCell><TableCell className="numeric">{money(fill.price)}</TableCell><TableCell className="numeric">{money(fill.quantity,4)}</TableCell><TableCell className="numeric">{money(fill.notional)}</TableCell></TableRow>)}</TableBody></Table><div className="open-range"><div><p className="eyebrow">OPEN-RANGE REFERENCE / NOT A FORECAST</p><h2>If the session anchor reprices by…</h2></div>{result.scenarios.map(scenario=><div key={scenario.move}><span>{signed(scenario.move,"%")} from anchor</span><strong>{money(scenario.price)}</strong><small>{signed(scenario.versusNow)} vs estimated fill</small></div>)}</div></Card></TabsContent>
          <TabsContent value="evidence"><Card className="evidence-card"><p className="eyebrow">SOURCES / BOUNDARIES</p><h2>What is observed, derived, and assumed.</h2><dl><dt>Observed market data</dt><dd>{snapshot.source==="live"?`Public Bitget v3 ticker and 50-level order book for ${snapshot.symbol}, timestamped ${time(snapshot.timestamp)}.`:"An illustrative fallback book. It is not presented as a live market observation."}</dd><dt>Derived session anchor</dt><dd>The close of the latest completed 3–4 PM New York hourly <em>rToken</em> candle on Bitget: {money(snapshot.anchor)} at {time(snapshot.anchorTimestamp)}. It is not the official underlying stock close.</dd><dt>Deterministic decision rule</dt><dd>Wait when visible depth cannot fill the order or when basis/spread/impact breaches the published demo thresholds. Size test is the middle state. Qwen does not set these values.</dd><dt>Not included</dt><dd>Fees, issuer redemption, taxes, hidden/RPI liquidity, price improvement, account balances, collateral treatment, or execution.</dd><dt>Live session</dt><dd>The US cash session is currently classified as {snapshot.session}. When it is open, the weekend-specific conclusion is less relevant.</dd></dl></Card></TabsContent>
        </Tabs></div>

        <aside className="trace-column"><Card className="trace-card"><div className="section-heading"><span><ScanSearch size={16}/>Agent run</span><span className="small-label">TRACE</span></div><div className="trace-body"><p className="hint">Five bounded steps answer one execution question.</p><AgentSteps steps={trace}/><div className="trace-status"><Check size={14}/>{loading?"Reading market":"Decision math complete"}</div></div></Card><Card className="agent-card"><div className="section-heading"><span><Sparkles size={16}/>Qwen brief</span><span className="small-label">OPTIONAL</span></div><div className="agent-body"><label htmlFor="research-note">Ask about this evidence</label><Textarea id="research-note" value={question} onChange={event=>setQuestion(event.target.value)} rows={3}/><Button className="research-button" onClick={askQwen} disabled={aiLoading||!question.trim()}>{aiLoading?"Researching…":"Explain this decision"}<ArrowRight size={14}/></Button>{aiText&&<p className="ai-output">{aiText}</p>}{aiError&&<p className="ai-error"><Unplug size={13}/>{aiError}</p>}<p className="hint">Model: Qwen 3.8 Max. No model text appears unless the server returns it.</p></div></Card><Card className="market-card"><div><Clock3 size={15}/><span>Snapshot</span></div><strong>{time(snapshot.timestamp)}</strong><div><BarChart3 size={15}/><span>24h turnover</span></div><strong>{compact(snapshot.platformTurnover24h)} USDT</strong><div><BookOpen size={15}/><span>Source</span></div><strong>{snapshot.source==="live"?"Bitget v3":"Illustrative"}</strong></Card></aside>
      </div><footer><span>VEYRA / COST-OF-IMMEDIACY DESK</span><span>Observed data + explicit assumptions</span><span>No login. No execution.</span></footer>
    </main>
  </div>
}
